<a href="https://colab.research.google.com/github/jakkulasanjay/digit_recognizer/blob/main/fake_news2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [39]:
import re

In [ ]:
data_false=pd.read_csv()
data_take=pd.read_csv()

In [2]:
import kagglehub
path = kagglehub.dataset_download("jruvika/fake-news-detection")

Downloading to /root/.cache/kagglehub/datasets/jruvika/fake-news-detection/1.archive...

100%|██████████| 4.89M/4.89M [00:00<00:00, 31.7MB/s]

Extracting files...

In [3]:
import os

print(os.listdir())

['.config', 'sample_data']

In [4]:
import os

for root, dirs, files in os.walk("/root/.cache/kagglehub"):
    for file in files:
        print(os.path.join(root, file))

/root/.cache/kagglehub/datasets/jruvika/fake-news-detection/1.complete
/root/.cache/kagglehub/datasets/jruvika/fake-news-detection/versions/1/data.csv
/root/.cache/kagglehub/datasets/jruvika/fake-news-detection/versions/1/data.h5

In [6]:
import pandas as pd

data = pd.read_csv(
    "/root/.cache/kagglehub/datasets/jruvika/fake-news-detection/versions/1/data.csv"
)

In [7]:
data

,URLs,Headline,Body,Label
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - “Last Flag Flying”, a comed...",1
2,https://www.nytimes.com/2017/10/09/us/politics...,Trump’s Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1
3,https://www.reuters.com/article/us-mexico-oil-...,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...,1
4,http://www.cnn.com/videos/cnnmoney/2017/10/08/...,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",1
...,...,...,...,...
4004,http://beforeitsnews.com/sports/2017/09/trends...,Trends to Watch,Trends to Watch\n% of readers think this story...,0
4005,http://beforeitsnews.com/u-s-politics/2017/10/...,Trump Jr. Is Soon To Give A 30-Minute Speech F...,Trump Jr. Is Soon To Give A 30-Minute Speech F...,0
4006,https://www.activistpost.com/2017/09/ron-paul-...,"Ron Paul on Trump, Anarchism & the AltRight",NaN,0
4007,https://www.reuters.com/article/us-china-pharm...,China to accept overseas trial data in bid to ...,SHANGHAI (Reuters) - China said it plans to ac...,1
4008,http://beforeitsnews.com/u-s-politics/2017/10/...,Vice President Mike Pence Leaves NFL Game Beca...,Vice President Mike Pence Leaves NFL Game Beca...,0

In [8]:
data.columns

Index(['URLs', 'Headline', 'Body', 'Label'], dtype='object')

In [14]:
print(data["Label"].value_counts())

Label
0    2137
1    1872
Name: count, dtype: int64

In [13]:
print(data["Label"].value_counts())

Label
0    2137
1    1872
Name: count, dtype: int64

In [16]:
data.isnull().sum()

URLs         0
Headline     0
Body        21
Label        0
dtype: int64

In [20]:
data=data.dropna()

In [21]:
data.isnull().sum()

URLs        0
Headline    0
Body        0
Label       0
dtype: int64

text preprocessing

In [23]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re

In [19]:
data.duplicated().sum()

np.int64(0)

In [30]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [33]:
ps=PorterStemmer()

#cleaning the text

In [38]:
def preprocess_text(text):
  #lower case conversion
  text=text.lower()
  #remove extra symbols
  text=re.sub(r'[^a-zA-Z\s]','',text)
  #tokenize
  word=word_tokenize(text)
  #stopword removal of 'a','an','the'
  new_text=[]
  for i in word:
    if i not in stopwords.words('english'):
        sam=ps.stem(i)
        new_text.append(sam)
      #stemming
  return ' '.join(new_text)

In [41]:
data.columns

Index(['URLs', 'Headline', 'Body', 'Label'], dtype='object')

applying the text_preprocessing function

In [61]:
data['Headline'] = data['Headline'].apply(preprocess_text)

/tmp/ipykernel_11162/1091505269.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Headline'] = data['Headline'].apply(preprocess_text)

dividing the dataset into X,y

In [62]:
X=data["Headline"]
y=data["Label"]

In [63]:
from sklearn.model_selection import train_test_split

train_test_split()

In [64]:

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# convert the text data into numerical data

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [66]:
X_train_tf=tf.fit_transform(X_train)

In [68]:
X_test_tf=tf.transform(X_test)

In [69]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

train model

In [70]:
model=lr.fit(X_train_tf,y_train)

predict model

In [71]:
pred=model.predict(X_test_tf)

In [72]:
print(pred[:3])

[0 0 1]

In [75]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,pred))

0.8345864661654135

In [74]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      0.85      0.85       450
           1       0.81      0.82      0.81       348

    accuracy                           0.83       798
   macro avg       0.83      0.83      0.83       798
weighted avg       0.83      0.83      0.83       798

In [77]:
print(confusion_matrix(y_test,pred))

[[382  68]
 [ 64 284]]